"""change in chunk_context table

Revision ID: 3b13b471ae97
Revises: 
Create Date: 2026-08-21 01:32:07.432911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b13b471ae97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_history', 'user_query',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_history', 'bot_response',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('context_chunks', sa.Column('source', sa.String(), nullable=True))
    op.add_column('context_chunks', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('context_chunks', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('context_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('context_chunks', sa.Column('row_number', sa.Integer(), nullable=True))
    op.alter_column('context_chunks', 'chunk_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('context_chunks', 'chunk_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('context_chunks', 'row_number')
    op.drop_column('context_chunks', 'page_number')
    op.drop_column('context_chunks', 'file_type')
    op.drop_column('context_chunks', 'file_name')
    op.drop_column('context_chunks', 'source')
    op.alter_column('chat_history', 'bot_response',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_history', 'user_query',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
